### ISSUE TITLE
Implement agreed file structure in shared AWS bucket for Living Maps data

### ISSUE THREAD

**Issue by LynnHeeley** [jncc/eo-workflows#6]
agree with Dan and guide him to implement or implement for him

**Comment by CathyJinJNCC** [comment]
We've decided to use the existing jncc-eo bucket which already has some version 3 sentinel 1 ard (instead of the s2 archive bucket with Pete Bunting's ard). We will use it as a generic ard bucket which we can put all future ard into. We've agreed with Gwawr to tag it with the eocoe project until she decides on a better project. We will copy across Pete Bunting's ard into jncc-eo so that NE have one bucket which they can find all their data in.

I have added Matt's proposed folder structure for s2 into that bucket and will create a new task for copying Pete Bunting's ard in.
